{
   "index":"logstash-2013.12.31",
   "topic":"dstat.ns3361853.cpu.user", 
   "query":{
      "facets":{
         "0":{
            "date_histogram":{
               "key_field":"@timestamp",
               "value_field":"cpuuser",
               "interval":"1s"
            },
            "facet_filter":{
               "fquery":{
                  "query":{
                     "filtered":{
                        "query":{
                           "query_string":{
                              "query":"host:ns3361853"
                           }
                        },
                        "filter":{
                           "bool":{
                              "must":[
                                 {
                                    "match_all":{

                                    }
                                 },
                                 {
                                    "fquery":{
                                       "query":{
                                          "field":{
                                             "_type":{
                                                "query":"\"dstat4\""
                                             }
                                          }
                                       },
                                       "_cache":true
                                    }
                                 },
                                 {
                                    "range":{
                                       "@timestamp":{
                                       "gt": "now-7200s",
                                       "lte": "now-7100s"
                                       }
                                    }
                                 },
                                 {
                                    "bool":{
                                       "must":[
                                          {
                                             "match_all":{

                                             }
                                          }
                                       ]
                                    }
                                 }
                              ]
                           }
                        }
                     }
                  }
               }
            }
         }
      },
      "size":0
   }
}